import { VerticalBox, ListView, Button, HorizontalBox } from "std-widgets.slint";
import { Account, ListData } from "global.slint";

//表内文本框
component TableText inherits Text {
    vertical-alignment: center;
    height: 30px;
    font-size: 15px;
}

//表头
component TableHead inherits Rectangle {
    //表头字体颜色
    in property <brush> tableHeadTextColor;

    width: 100%;
    height: 50px;
    background: #323133;
    tableHeadTextColor: white;
     
    HorizontalBox {
        TableText { width:  40px; text: "序号"; color: tableHeadTextColor; }
        TableText { width: 400px; text: "网址"; color: tableHeadTextColor; }
        TableText { width: 150px; text: "账号"; color: tableHeadTextColor; }
        TableText { width: 250px; text: "邮箱"; color: tableHeadTextColor; }
        TableText { width: 100px; text: "手机号"; color: tableHeadTextColor; } 
        TableText { width: 200px; text: "密码"; color: tableHeadTextColor; }
        TableText { width: 100px; text: "操作"; color: tableHeadTextColor; horizontal-alignment: center; }
    }
}

//表体
component TableBody inherits Rectangle {
    in property <Account> itemData;
    in property <brush> backgroundColor;

    width: 100%;
    height: 40px;
    background: backgroundColor;

    //编辑
    callback edit();

    //删除
    callback delete();
    
    HorizontalBox {
        TableText { width: 40px; text: itemData.id; }
        TableText { width: 400px; text: itemData.website; }
        TableText { width: 150px; text: itemData.account; }
        TableText { width: 250px; text: itemData.email; }
        TableText { width: 100px; text: itemData.phone; }
        TableText { width: 200px; text: itemData.password; }
        HorizontalLayout {
            width: 100px;
            height: 30px;
            alignment: center;
            spacing: 10px;

            Button { text: "编辑";  clicked => { root.edit() } }
            Button { text: "删除";  clicked => { root.delete() } }
        } 
    } 
}

//表格内容
export component MainWindowContent inherits VerticalBox {
    width: 95%;
    height: 90%;
    visible: true;
    y: 0px;

    //编辑
    callback edit(id: int, website: string, account: string, email: string, phone: string, password: string);

    //删除
    callback delete(id: int);

    TableHead {}

    ListView {
        for item[i] in ListData.list : TableBody {
            itemData: item;
            backgroundColor: 0 == mod(i, 2) ? #CCD1D9 : #AAB2BD;

            //点击编辑按钮
            edit => {
                root.edit(self.itemData.id, self.itemData.website, self.itemData.account, self.itemData.email, self.itemData.phone, self.itemData.password);
            }

            //点击删除按钮
            delete => {
                root.delete(self.itemData.id);
            }
        }
    }
}