import { LineEdit, Button, VerticalBox } from "std-widgets.slint";
export component EditWindowContent inherits Rectangle {
    //创建
    visible: false;
    width: 300px;
    height: 500px;
    z: 20;
    background: white;
    border-radius: 10px;

    callback close();

    Rectangle {
        x: 0;
        y: 0;
        width: 100%;
        height: 40px;
        background: #03a9f4;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;

        Text { 
            text: "编辑";
            font-size: 25px;
            horizontal-alignment: center;
        }
    }

    VerticalBox {
        width: 250px;
        alignment: center;
        spacing: 20px;

        LineEdit { height: 40px; placeholder-text: "网址"; }
        LineEdit { height: 40px; placeholder-text: "账号"; }
        LineEdit { height: 40px; placeholder-text: "邮箱"; }
        LineEdit { height: 40px; placeholder-text: "手机号"; }
        LineEdit { height: 40px; placeholder-text: "密码"; }

        Button {
            text: "生成随机密码";
            height: 40px;
            clicked => {
                debug("生成随机密码");
            }
        }

        HorizontalLayout {
            alignment: space-around;
            Button { 
                text: "保存"; 
                primary: true; 
                width: 100px;
                height: 40px;
                clicked => {
                    root.close();
                } 
            }

            Button {
                text: "关闭";
                width: 100px;
                height: 40px;
                clicked => {
                    root.close();
                }
            }
        } 
    }
}