import { VerticalBox, Button, HorizontalBox, LineEdit } from "std-widgets.slint";

//登录窗口
export component LoginWindowContent inherits Rectangle {
    in-out property <string> pwd;
    in-out property <string> alert_text: "";

    background: white;
    visible: false;

    callback close();

    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            alignment: space-around;
            Image {
                width: 100px;
                height: 100px;
                x: 50px; 
                source: @image-url("icons/logo_big.png");
            }

            LineEdit {
                width: 200px;
                height: 40px;
                font-size: 20px;
                placeholder-text: "请输入密码";
                input-type: password;

                edited(text) => {
                    root.pwd = text;
                    root.alert_text = "";
                }
            }

            Text {
                text: alert_text;
                color: red;
                font-size: 10px;
            }

            Button {
                width: 200px;
                height: 40px;
                text: "登录";
                primary: true;
                clicked => {
                    debug("登录");
                    root.close();
                }
            }
        }
    }
}