import { VerticalBox, Button, HorizontalBox, LineEdit } from "std-widgets.slint";

//登录窗口
export component LoginWindowContent inherits Rectangle {
    width: 300px;
    height: 400px;
    x: 550px;
    z: 20;
    background: white;
    border-radius: 10px;
    visible: false;

    callback close();

    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            alignment: space-around;
            Image {
                width: 100px;
                height: 100px;
                x: 50px; 
                source: @image-url("icons/tile_logo.png");
            }

            LineEdit {
                width: 200px;
                height: 40px;
                font-size: 20px;
            }

            Button {
                width: 200px;
                height: 40px;
                text: "登录";
                primary: true;
                clicked => {
                    debug("登录");
                    root.close();
                }
            }
        }
    }
}