import { LineEdit, Button, VerticalBox } from "std-widgets.slint";
export component PasswordWindowContent inherits Rectangle {
    //修改密码
    visible: false;
    width: 300px;
    height: 400px;
    z: 20;
    background: white;
    border-radius: 10px;

    callback close();

    Rectangle {
        x: 0;
        y: 0;
        width: 100%;
        height: 40px;
        background: #03a9f4;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;

        Text { 
            text: "修改密码";
            font-size: 25px;
            horizontal-alignment: center;
        }
    }

    VerticalBox {
        width: 250px;
        alignment: center;
        spacing: 20px;

        LineEdit { height: 40px; placeholder-text: "新密码"; }
        LineEdit { height: 40px; placeholder-text: "确认密码"; }

        Button { 
            text: "保存"; 
            primary: true; 
            height: 40px;
            clicked => {
                root.close();
            } 
        }
    }
}